#!/usr/bin/env bash
# manage_my_process Bash script

start_process() {
    # Start manage_my_process
    ./manage_my_process &
    # Get the PID of the process
    pid=$!
    # Save PID to /var/run/my_process.pid
    echo $pid > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop_process() {
    # Check if the process is running
    if [ -e /var/run/my_process.pid ]; then
        # Read PID from file
        pid=$(cat /var/run/my_process.pid)
        # Kill the process
        kill $pid
        echo "manage_my_process stopped"
        # Remove PID file
        rm /var/run/my_process.pid
    else
        echo "No running process found"
    fi
}

restart_process() {
    # Stop the process if it's running
    stop_process
    # Start the process
    start_process
    echo "manage_my_process restarted"
}

# Check argument
case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
